Get all user from database
IA-Fuad/BlazorApp pull request #3
Opened 2021-02-09 05:44 UTC by IA-Fuad

API to retrieve data from database

2021-02-09 09:02 UTC, sahariar-tomal requested changes
Please resolve this issues.

2021-02-09 09:02 UTC, sahariar-tomal commented on BlazorAppAPI/Services/IProjectService.cs
> +                throw;
We should not throw exception like this. We need to handle this properly. We can use logging mechanism for this. Or we can return null object and check in controller if it is null then return response with appropriate wordings like Could not create project.

2021-02-09 09:02 UTC, sahariar-tomal commented on BlazorAppAPI/Services/IProjectService.cs
> +                throw;
same here.

2021-02-09 09:02 UTC, sahariar-tomal commented on BlazorAppAPI/Services/IProjectService.cs
> +                throw;
Same here

2021-02-09 09:51 UTC, IA-Fuad commented on BlazorAppAPI/Controllers/AccountController.cs
> +       // [Authorize(Roles = "Admin")]
Needed to create users for testing purposes. Authorize tag requires to pass jwt token every time to do that. I will uncomment it before merging to the master branch.

2021-02-09 09:53 UTC, IA-Fuad commented on BlazorAppAPI/Controllers/ProjectController.cs
> +    public class ProjectController : ControllerBase
Only the register method will be restricted to the admin. But the login method can be used by everyone.

2021-02-09 09:53 UTC, IA-Fuad commented on BlazorAppAPI/Services/IProjectService.cs
> +                throw;
Working on this now.

2021-02-09 10:17 UTC, sahariar-tomal requested changes

2021-02-09 10:17 UTC, sahariar-tomal commented on BlazorAppAPI/Controllers/ProjectController.cs
> +    public class ProjectController : ControllerBase
But here we are in Projects controller and it has endpoints like GetAllProjects, GetProjectById, CreateProject, UpdateProject etc. So these should not be accessed by unauthorized users.

2021-02-09 10:17 UTC, sahariar-tomal commented on BlazorAppAPI/Controllers/AccountController.cs
> +       // [Authorize(Roles = "Admin")]
You can have some local changes for faster testing but when we create PR we should not have changes like that. You can apply your local changes whenever you want.

2021-02-09 10:20 UTC, IA-Fuad commented on BlazorAppAPI/Controllers/ProjectController.cs
> +    public class ProjectController : ControllerBase
My bad. I thought it was AccountController. Fixing it now.

2021-02-09 14:43 UTC, sahariar-tomal requested changes
The idea for a generic service for doing CRUD is really awesome. But the name should be more meaningful.

2021-02-09 14:43 UTC, sahariar-tomal commented on BlazorAppAPI/Services/ICUD.cs
> +    public interface ICUD
The name should be more meaningful.

2021-02-09 14:47 UTC, IA-Fuad commented on BlazorAppAPI/Services/ICUD.cs
> +    public interface ICUD
Will change that.

2021-02-09 15:38 UTC, sahariar-tomal approved these changes
👍

2021-02-10 07:20 UTC, sahariar-tomal approved these changes
👍

2021-02-10 07:22 UTC, merged